### ISSUE TITLE
关于选择弹幕类型时候的样式问题

### ISSUE THREAD

**Issue by ghost** [MoePlayer/react-dplayer#124]
你好，在选择弹幕类型的时候样式貌似有点问题：
![problem](https://user-images.githubusercontent.com/62355044/89122548-94b4a280-d4fa-11ea-9765-6409fbc83bc6.png)

因为我在官网的例子看到的样式是正常的，所以就来你这里提issue了= =（也有可能是我自己的问题
![normal](https://user-images.githubusercontent.com/62355044/89122579-bada4280-d4fa-11ea-9379-1bf2670796b1.png)

目前Chrome和Safari都有这个问题，所以应该不是浏览器的问题。

暂时的解决方案是额外重写宽度把33%改成100%：
<img width="941" alt="temporary_solution" src="https://user-images.githubusercontent.com/62355044/89122611-19072580-d4fb-11ea-81b8-01829ffbb155.png">

但是我看了官网的对应样式，也是33%，不知道是哪里出了问题，请求帮助，谢谢！

**Comment by hnsylitao** [comment]
https://codesandbox.io/s/elated-yalow-4ry4u
这个问题我写了一个codesandbox 没有发现问题哦，你可以试着写一个最小可复现的案例，再来排除。
可能导致问题原因是一些其他的样式导致的。
