### ISSUE TITLE
关于切换视频switchVideo的问题

### ISSUE THREAD

**Issue by ghost** [MoePlayer/react-dplayer#128]
你好，我在切换视频的时候使用了onLoad获取了dplayer对象，然后对其使用switchVideo方法时，根据我的config对象传入了相应的video和danmaku参数，
可是我的config对象是包含三种清晰度的，例如：
```
const config = {
	video: {
		quality: [
			{
				name: "LD",
				url: url_LD,
			},
			{
				name: "SD",
				url: url_SD,
			},
			{
				name: "HD",
				url: url_HD,
			},
		],
		defaultQuality: 2,
                // url: url_HD, <--------- 这一行先注释掉
	},
	danmaku: {
		...
	},
};
```
如果我直接使用`dplayer.switchVideo(config.video, config.danmaku);`会显示视频无法加载，DPlayer的src是undefined，所以我在video里额外添加了一行url（就是取消上面url的注释）后，视频是可以成功切换了，但是只有这个清晰度（例如这里的HD）是【切换后】的视频，如果此时再切换到别的清晰度（例如LD或SD），就会变成【切换前】的视频了，请问一下有没有什么解决的办法？

**Comment by hnsylitao** [comment]
http://dplayer.js.org/zh/guide.html#api
如果已经初始化好了 清晰度可以 switchQuality

**Comment by hnsylitao** [comment]
switchVideo 我看了下dplayer js 源代码是不支持切换整体的清晰度地址的。

**Comment by ghost** [comment]
好的，感谢回复！另外请问一下react里该如何获取切换清晰度的点击事件呢

**Comment by hnsylitao** [comment]
可以自己获取dplayer template dom节点自己绑定事件
