### ISSUE TITLE
移动端播放时，会有一个暂停按钮一直在屏幕上。

### ISSUE THREAD

**Issue by easychen** [MoePlayer/react-dplayer#143]
移动端播放时，会有一个暂停按钮一直在屏幕上。

重现方法：

- 打开 demo https://codesandbox.io/s/react-dplayer-demo-i61n5  
- 通过 devtools 将界面设置手机，刷新
- 播放，即可看到暂停图标
![image](https://user-images.githubusercontent.com/1294760/92592599-6af95300-f2d2-11ea-95b1-1fe60ccabe3f.png)

**Comment by hnsylitao** [comment]
这个问题可以去dplayer去提问哦。dplayer 目前应该是没有做移动端样式兼容。

**Comment by easychen** [comment]
> 这个问题可以去dplayer去提问哦。dplayer 目前应该是没有做移动端样式兼容。

但是 D-player 本身并没有这个问题呀。 

访问 https://dplayer.js.org/ 然后将 devtools 切换到 手机，可以看大播放中并没有暂停符号。


![image](https://user-images.githubusercontent.com/1294760/93203724-78598600-f787-11ea-8f5a-80556f8a37ab.png)

**Comment by easychen** [comment]
> 这个问题可以去dplayer去提问哦。dplayer 目前应该是没有做移动端样式兼容。

好的。之前测试的时候没发现官网也是这样的。
