### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trigger' of undefined

### ISSUE THREAD

**Issue by Tian0301** [MoePlayer/react-dplayer#2]
在弹窗中使用播放器播放，关闭弹窗的同时 将播放器移出，就会出现这种错误？ 不影响播放

版本是 0.2.0,   在上一个版本中就不会出现这个错误 @hnsylitao

**Comment by DIYgod** [comment]
@TSywan 使用 destroy 销毁播放器出现报错为上游仓库 DPlayer 的已知 bug，请等待上游仓库更新

**Comment by Tian0301** [comment]
OK  谢谢解答
