### ISSUE TITLE
未实现接收Options的Props更新

### ISSUE THREAD

**Issue by dev-techmoe** [MoePlayer/react-dplayer#31]
似乎现在更新`options`没有效果？
demo: https://codesandbox.io/s/problem-with-dplayer-recv-props-y1eur
更新props中的`options`之后播放器并未正确切换视频，浏览相关代码发现似乎也并未实现，是我的用法有问题还是这一块确实存在问题？

**Comment by hnsylitao** [comment]
dplayer 不对options 更新。
可以通过 onLoad 获取到 player 的实例。
在去通过player switchVideo 来切换视频

**Comment by hnsylitao** [comment]
#5 可以参考这个问题。可以在顶层封装一层。 url 更新 手动触发api swtichVideo 来切换视频

**Comment by dev-techmoe** [comment]
感谢提示，问题已解决
