### ISSUE TITLE
logo不显示

### ISSUE THREAD

**Issue by flymzero** [MoePlayer/react-dplayer#4]
按照文档和你的demo,logo还是不显示

export function FuncVideoPlayer(picStr, urlStr, isLive){
	return(
		<Dplayer
			theme={'#1890ff'}
			live={isLive}
    		logo={'http://static.smartisanos.cn/pr/img/video/video_03_cc87ce5bdb.jpg'}
     		video={
       			{
					pic: picStr,
       				url: urlStr,
     				type:'auto'
    			}
    	}/>
	)
}

**Comment by Re-Make-Re-Model** [comment]
@flymzero 你这个图片不存在，打不开？是后来删除了吗？
{"errorcode":-46628,"errormsg":"file not exist, retcode:-46628"}

**Comment by hnsylitao** [comment]
https://codepen.io/hnsylitao/pen/ePWKBK/
@flymzero 我试了下没有复现你的问题

**Comment by flymzero** [comment]
@hnsylitao 我查到是logo的img标签高度为0 了，应该是我自己项目问题，我css手动调整了，谢谢答复
