### ISSUE TITLE
示例写错了

### ISSUE THREAD

**Issue by Microbai** [MoePlayer/react-dplayer#7]
应该是import DPlayer from 'react-dplayer'; 而不是 import Dplayer from 'react-dplayer';

**Comment by hnsylitao** [comment]
好的，谢谢啦～

**Comment by jhxxs** [comment]
next demo里第32行`false`写成了`fasle`

**Comment by hnsylitao** [comment]
> next demo里第32行`false`写成了`fasle`

谢谢了，已经更正。
