### ISSUE TITLE
样式加载异常

### ISSUE THREAD

**Issue by coder-xsy** [MoePlayer/react-dplayer#8]
在create-react-app创建的项目中使用react-dplayer后刷新页面，dplayer的样式初始的时候会无效（设置按钮中的内容），导致设置按钮中的内容显示的样式混乱，这个问题目前我还没解决，所以想请教一下

**Comment by hnsylitao** [comment]
参考一下我readme 给出的 demo
如果还有问题，给出codesandbox 地址我排查一下
