### ISSUE TITLE
希望添加d.ts声明文件，方便typescript环境下使用

### ISSUE THREAD

**Issue by 463010817** [MoePlayer/react-dplayer#9]

**Comment by Copay** [comment]
@463010817 自己动手，丰衣足食。

**Comment by hnsylitao** [comment]
等会我更新一下 你到时候升级一下就能够支持了

**Comment by hnsylitao** [comment]
npm install react-dplayer@0.3.3 -S

注意下 重新看下readme，对应的属性也改变了
所有的options 都放到 options 属性下了
