### ISSUE TITLE
Safari浏览器下的清晰度切换bug

### ISSUE THREAD

**Issue by ghost** [MoePlayer/react-dplayer#98]
你好，好像播放器在Safari浏览器下切换清晰度的时候会卡住，包括文档里demo的例子也有这个问题，请问有解决方案吗～

**Comment by hnsylitao** [comment]
请问可以提供浏览器版本嘛，我没有测试出来。
你说得卡住，是说浏览器卡死了，还是说视频暂停播放了呢？

**Comment by ghost** [comment]
你好，Safari版本是13.1.1 (15609.2.9.1.2)
我录了一段视频你可以看一下
[issue98.zip](https://github.com/MoePlayer/react-dplayer/files/4750789/issue98.zip)

**Comment by hnsylitao** [comment]
这个问题需要像dplayer.js 反馈，还需要了解视频格式情况，具体定位问题哦

**Comment by ghost** [comment]
好的，十分感谢！请问需要我在dplayer.js下重新提issue嘛？还是你们是一块的。。。。。

**Comment by hnsylitao** [comment]
@Youguang-Zhou 在dplayer.js提交issue把
